# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#11111b"
theme_background=true

# Main text color
theme[main_fg]="#cad3f5"

# Title color for boxes
theme[title]="#fab387"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#fab387"

# Background color of selected item in processes box
theme[selected_bg]="#313244"

# Foreground color of selected item in processes box
theme[selected_fg]="#cad3f5"

# Color of inactive/disabled text
theme[inactive_fg]="#5b6078"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#fab387"

# Box outline and divider line color
theme[cpu_box]="#fab387"
theme[mem_box]="#fab387"
theme[net_box]="#fab387"
theme[proc_box]="#fab387"
theme[div_line]="#313244"

# Gradient for all meters and graphs
theme[temp_start]="#fab387"
theme[temp_mid]="#eed49f"
theme[temp_end]="#a6da95"

theme[cpu_start]="#fab387"
theme[cpu_mid]="#eed49f"
theme[cpu_end]="#a6da95"

theme[free_start]="#8bd5ca"
theme[free_mid]="#8aadf4"
theme[free_end]="#8aadf4"

theme[cached_start]="#8aadf4"
theme[cached_mid]="#8aadf4"
theme[cached_end]="#8bd5ca"

theme[available_start]="#a6da95"
theme[available_mid]="#8bd5ca"
theme[available_end]="#8bd5ca"

theme[used_start]="#fab387"
theme[used_mid]="#eed49f"
theme[used_end]="#ed8796"

theme[download_start]="#8aadf4"
theme[download_mid]="#8aadf4"
theme[download_end]="#8bd5ca"

theme[upload_start]="#fab387"
theme[upload_mid]="#eed49f"
theme[upload_end]="#ed8796"
