;;; Coppernight for Emacs — deep indigo + glowing copper
;;; Install: copy to ~/.emacs.d/themes/coppernight-theme.el,
;;;   then (add-to-list 'custom-theme-load-path "~/.emacs.d/themes/")
;;;   and M-x load-theme RET coppernight RET

(deftheme coppernight
  "Deep indigo canvas with glowing copper accents.")

(let ((bg         "#11111b")
      (bg-dark    "#0b0b12")
      (panel      "#181825")
      (sel        "#313244")
      (fg         "#cad3f5")
      (fg-bright  "#a5adcb")
      (muted      "#5b6078")
      (dim        "#6e738d")
      (copper     "#fab387")
      (red        "#ed8796")
      (green      "#a6da95")
      (yellow     "#eed49f")
      (blue       "#8aadf4")
      (mauve      "#c6a0f6")
      (teal       "#8bd5ca")
      (pink       "#f5bde6"))
  (custom-theme-set-faces
   'coppernight
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,red))))
   `(region ((t (:background ,sel :foreground ,fg))))
   `(highlight ((t (:background ,sel :foreground ,fg))))
   `(fringe ((t (:background ,bg :foreground ,muted))))
   `(linum ((t (:background ,bg :foreground ,fg-bright))))
   `(line-number ((t (:background ,bg :foreground ,fg-bright))))
   `(line-number-current-line ((t (:background ,bg :foreground ,copper :weight bold))))
   `(minibuffer-prompt ((t (:foreground ,copper :weight bold))))
   `(mode-line ((t (:background ,panel :foreground ,fg :box (:line-width 1 :color ,sel)))))
   `(mode-line-inactive ((t (:background ,bg-dark :foreground ,dim :box (:line-width 1 :color ,bg-dark)))))
   `(mode-line-buffer-id ((t (:foreground ,copper :weight bold))))
   `(vertical-border ((t (:foreground ,sel))))
   `(window-divider ((t (:foreground ,sel))))
   `(window-divider-first-pixel ((t (:foreground ,sel))))
   `(window-divider-last-pixel ((t (:foreground ,sel))))
   ;; Syntax
   `(font-lock-comment-face ((t (:foreground ,fg-bright :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,fg-bright :slant italic))))
   `(font-lock-doc-face ((t (:foreground ,fg-bright :slant italic))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-constant-face ((t (:foreground ,copper))))
   `(font-lock-builtin-face ((t (:foreground ,teal))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   `(font-lock-variable-use-face ((t (:foreground ,fg))))
   `(font-lock-function-name-face ((t (:foreground ,blue :weight bold))))
   `(font-lock-function-call-face ((t (:foreground ,blue))))
   `(font-lock-keyword-face ((t (:foreground ,mauve))))
   `(font-lock-type-face ((t (:foreground ,yellow))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(font-lock-preprocessor-face ((t (:foreground ,yellow))))
   `(font-lock-regexp-face ((t (:foreground ,mauve))))
   `(font-lock-number-face ((t (:foreground ,copper))))
   `(font-lock-operator-face ((t (:foreground ,teal))))
   `(font-lock-punctuation-face ((t (:foreground ,dim))))
   `(font-lock-property-name-face ((t (:foreground ,teal))))
   `(font-lock-property-use-face ((t (:foreground ,teal))))
   ;; Search / matching
   `(isearch ((t (:background ,yellow :foreground ,bg-dark :weight bold))))
   `(lazy-highlight ((t (:background ,sel :foreground ,fg))))
   `(show-paren-match ((t (:background ,sel :foreground ,copper :weight bold))))
   `(show-paren-mismatch ((t (:background ,red :foreground ,bg :weight bold))))
   ;; Completion / UI
   `(completions-common-part ((t (:foreground ,copper))))
   `(completions-first-difference ((t (:foreground ,copper :weight bold))))
   `(link ((t (:foreground ,blue :underline t))))
   `(link-visited ((t (:foreground ,mauve :underline t))))
   `(success ((t (:foreground ,green))))
   `(warning ((t (:foreground ,yellow))))
   `(error ((t (:foreground ,red))))
   `(header-line ((t (:background ,panel :foreground ,fg))))
   `(tooltip ((t (:background ,panel :foreground ,fg))))
   `(secondary-selection ((t (:background ,sel))))
   `(trailing-whitespace ((t (:background ,red))))
   ;; Dired / files — bright names on dark canvas
   `(dired-directory ((t (:foreground ,blue :weight bold))))
   `(dired-flagged ((t (:foreground ,red))))
   `(dired-marked ((t (:foreground ,copper :weight bold))))
   `(dired-symlink ((t (:foreground ,teal))))
   `(dired-broken-symlink ((t (:background ,red :foreground ,bg :weight bold))))
   ;; Diff
   `(diff-added ((t (:foreground ,green))))
   `(diff-removed ((t (:foreground ,red))))
   `(diff-changed ((t (:foreground ,yellow))))
   `(diff-refine-added ((t (:background ,sel :foreground ,green))))
   `(diff-refine-removed ((t (:background ,sel :foreground ,red))))
   ;; Org
   `(org-level-1 ((t (:foreground ,red :weight bold))))
   `(org-level-2 ((t (:foreground ,green :weight bold))))
   `(org-level-3 ((t (:foreground ,yellow :weight bold))))
   `(org-level-4 ((t (:foreground ,blue :weight bold))))
   `(org-level-5 ((t (:foreground ,mauve :weight bold))))
   `(org-link ((t (:foreground ,blue :underline t))))
   `(org-code ((t (:foreground ,green))))
   `(org-block ((t (:background ,panel :foreground ,fg))))
   `(org-block-begin-line ((t (:background ,panel :foreground ,dim))))
   `(org-block-end-line ((t (:background ,panel :foreground ,dim))))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'coppernight)
